### ISSUE TITLE
"openmath" rendering quality worse than "master" branch

### ISSUE THREAD

**Issue by LiuPeiqiCN** [NanoMichael/MicroTeX#159]
![image](https://github.com/NanoMichael/MicroTeX/assets/7535781/274f8702-2f5c-46dd-afe3-009a700fa74a)
![image](https://github.com/NanoMichael/MicroTeX/assets/7535781/20fdf3db-cc16-4342-83aa-2e2f7b9faa8c)
The rendering quality on the right side is noticeably worse, with significantly more font aliasing.

**Comment by NanoMichael** [comment]
It seems that the scaling ratio is set incorrectly. Please try changing it here: https://github.com/NanoMichael/MicroTeX/blob/c846d9c8d0e0772b9bcea4092c3cbcebdf3ee92c/example/qt/qt_skiatexwidget.cpp#L92

I currently don't have much time to maintain this project.

**Comment by LiuPeiqiCN** [comment]
Must set `microtex::MicroTeX::setRenderGlyphUsePath(true)`

**Comment by sp1ritCS** [comment]
@LiuPeiqiCN calling `setRenderGlyphUsePath` seems more like a workaround than actually fixing the issue.
When this is set to false, skia is responsible for rendering the proper glyph based on it's unicode number, otherwise skia will just receive vector instructions on how to draw the glyph.

This might imply that skia attempts to cache glyphs in some sort of texture atlas that isn't using the proper resolution on HiDPI.
When you draw latin text to a skia surface, is that text then also blurry?
