### ISSUE TITLE
\dfrac 不显示分子分母间的横线

### ISSUE THREAD

**Issue by LiuPeiqiCN** [NanoMichael/MicroTeX#162]
\dfrac比较常用到，但是发现没有分数线了
![image](https://github.com/NanoMichael/MicroTeX/assets/7535781/959eb1f2-3766-427f-b8fd-f9cebae88e58)

**Comment by sp1ritCS** [comment]
If I have understood you correctly, #164 should fix this.

Instead of using `\dfrac` you might want to consider setting `\everymath{\displaystyle}` or run [`microtex::MicroTeX::overrideTexStyle(true, microtex::TextStyle::display)`](https://github.com/NanoMichael/MicroTeX/blob/53f2a90b86c9f1a1e27f9b96b620d85f6115a105/lib/microtex.h#L134)

**Comment by NanoMichael** [comment]
fixed by #164
